### ISSUE TITLE
Is the `e14n` example wrong?

### ISSUE THREAD

**Issue by jamietanna** [igb/numeronymize#1]
Or is `e14n` instead of `a16z` a joke I've missed?

**Comment by igb** [comment]
Sorry, yes, it is a joke. As with many of my jokes I often have to explain them. That means they are funny, right? 

Anyway, as you may be aware, "e14n" is a numeronym for Cory Doctorow's recently coined concept  of "enshittification". 

Andreesen Horowitz, as you point out, often refer to themselves using the numeronym "a16z".

Thought it would be funny to conflate the two. :-)

**Comment by jamietanna** [comment]
Ah yes, I had wondered if _maybe_ that's what we were going for - thanks for the confirmation 😂
